#!/bin/sh
echo ""
echo "========================================="
echo "  Ephemeris is running"
echo "  HTTP:  http://localhost:80"
echo "  HTTPS: https://localhost:443"
echo ""
echo "  To enable offline PWA, install the CA"
echo "  cert in your OS trust store:"
echo "    https://localhost:443/ca.crt"
echo ""
echo "  Or extract it from the container:"
echo "    docker cp <container>:/certs/ephemeris-ca.crt ."
echo "========================================="
echo ""
exec nginx -g "daemon off;"
